### ISSUE TITLE
Root of a server is always seen as relative

### ISSUE THREAD

**Issue by PukieDiederik** [PukieDiederik/webserv#32]
When the path of a root starts with `/` (like `/var/www`) it means its absolute (So full path would be `/var/www/`). If the root starts without a `/` it should be relative (for example if it's located in `/home/drobert`, the full path would be `/home/drobert/var/www`). In our case it always assumes the path is relative. We might want to make sure the path is always absolute (so require a `/` before the path), or we should do it relative to the config file.

**Comment by gde-alme** [comment]
Should already be solved by my previous pull request

**Comment by gde-alme** [comment]
Actually this can and will be improved in my next commit to either find said absolute path or in config file , "root" must be an absolute path

**Comment by gde-alme** [comment]
Actually, was already set, added checking if path is valid or not
 Editing my previous edit to the Server.cpp file (the "." before root)
Should work fine now, assuming given path in root tag is an absolute path
